FROM eisoku9618/kuroiwa_dockefiles_for_jsk_ros_pkg:depend

ARG ROS_INSTALLDIR=/root/catkin_ws/indigo
ARG ROS_INSTALLDIR_PARENT_SRC=${ROS_INSTALLDIR}_parent/src/

# build non-ros packages and then build ros packages (chain)
SHELL ["/bin/bash", "-c"]
RUN source /opt/ros/indigo/setup.bash \
&& cd ${ROS_INSTALLDIR_PARENT_SRC}/../ \
&& catkin build

CMD ["bash"]
