FROM ubuntu:19.10

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y --no-install-recommends \
# for (u)platex
texlive-lang-french \
# for CTAN packages
texlive-plain-generic texlive-latex-base texlive-latex-extra \
# for latexmk
latexmk \
# for extra fonts
texlive-fonts-recommended \
&& rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
